/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type OrderInfoStruct = {
  reactor: AddressLike;
  swapper: AddressLike;
  nonce: BigNumberish;
  deadline: BigNumberish;
  additionalValidationContract: AddressLike;
  additionalValidationData: BytesLike;
};

export type OrderInfoStructOutput = [
  reactor: string,
  swapper: string,
  nonce: bigint,
  deadline: bigint,
  additionalValidationContract: string,
  additionalValidationData: string
] & {
  reactor: string;
  swapper: string;
  nonce: bigint;
  deadline: bigint;
  additionalValidationContract: string;
  additionalValidationData: string;
};

export type InputTokenStruct = {
  token: AddressLike;
  amount: BigNumberish;
  maxAmount: BigNumberish;
};

export type InputTokenStructOutput = [
  token: string,
  amount: bigint,
  maxAmount: bigint
] & { token: string; amount: bigint; maxAmount: bigint };

export type OutputTokenStruct = {
  token: AddressLike;
  amount: BigNumberish;
  recipient: AddressLike;
};

export type OutputTokenStructOutput = [
  token: string,
  amount: bigint,
  recipient: string
] & { token: string; amount: bigint; recipient: string };

export type ResolvedOrderStruct = {
  info: OrderInfoStruct;
  input: InputTokenStruct;
  outputs: OutputTokenStruct[];
  sig: BytesLike;
  hash: BytesLike;
};

export type ResolvedOrderStructOutput = [
  info: OrderInfoStructOutput,
  input: InputTokenStructOutput,
  outputs: OutputTokenStructOutput[],
  sig: string,
  hash: string
] & {
  info: OrderInfoStructOutput;
  input: InputTokenStructOutput;
  outputs: OutputTokenStructOutput[];
  sig: string;
  hash: string;
};

export interface OrderQuoterInterface extends Interface {
  getFunction(
    nameOrSignature: "getReactor" | "quote" | "reactorCallback"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getReactor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quote",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reactorCallback",
    values: [ResolvedOrderStruct[], BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getReactor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactorCallback",
    data: BytesLike
  ): Result;
}

export interface OrderQuoter extends BaseContract {
  connect(runner?: ContractRunner | null): OrderQuoter;
  waitForDeployment(): Promise<this>;

  interface: OrderQuoterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReactor: TypedContractMethod<[order: BytesLike], [string], "view">;

  quote: TypedContractMethod<
    [order: BytesLike, sig: BytesLike],
    [ResolvedOrderStructOutput],
    "nonpayable"
  >;

  reactorCallback: TypedContractMethod<
    [resolvedOrders: ResolvedOrderStruct[], arg1: BytesLike],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReactor"
  ): TypedContractMethod<[order: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "quote"
  ): TypedContractMethod<
    [order: BytesLike, sig: BytesLike],
    [ResolvedOrderStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reactorCallback"
  ): TypedContractMethod<
    [resolvedOrders: ResolvedOrderStruct[], arg1: BytesLike],
    [void],
    "view"
  >;

  filters: {};
}
