/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type SignedOrderStruct = { order: BytesLike; sig: BytesLike };

export type SignedOrderStructOutput = [order: string, sig: string] & {
  order: string;
  sig: string;
};

export interface RelayOrderReactorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PERMIT2"
      | "execute((bytes,bytes))"
      | "execute((bytes,bytes),address)"
      | "multicall"
      | "permit"
      | "universalRouter"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Relay"): EventFragment;

  encodeFunctionData(functionFragment: "PERMIT2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "execute((bytes,bytes))",
    values: [SignedOrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "execute((bytes,bytes),address)",
    values: [SignedOrderStruct, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multicall",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "permit",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "universalRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "PERMIT2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "execute((bytes,bytes))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "execute((bytes,bytes),address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multicall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "permit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "universalRouter",
    data: BytesLike
  ): Result;
}

export namespace RelayEvent {
  export type InputTuple = [
    orderHash: BytesLike,
    filler: AddressLike,
    swapper: AddressLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    orderHash: string,
    filler: string,
    swapper: string,
    nonce: bigint
  ];
  export interface OutputObject {
    orderHash: string;
    filler: string;
    swapper: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RelayOrderReactor extends BaseContract {
  connect(runner?: ContractRunner | null): RelayOrderReactor;
  waitForDeployment(): Promise<this>;

  interface: RelayOrderReactorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PERMIT2: TypedContractMethod<[], [string], "view">;

  "execute((bytes,bytes))": TypedContractMethod<
    [signedOrder: SignedOrderStruct],
    [void],
    "nonpayable"
  >;

  "execute((bytes,bytes),address)": TypedContractMethod<
    [signedOrder: SignedOrderStruct, feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  multicall: TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;

  permit: TypedContractMethod<
    [
      token: AddressLike,
      owner: AddressLike,
      spender: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  universalRouter: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PERMIT2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute((bytes,bytes))"
  ): TypedContractMethod<
    [signedOrder: SignedOrderStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "execute((bytes,bytes),address)"
  ): TypedContractMethod<
    [signedOrder: SignedOrderStruct, feeRecipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multicall"
  ): TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;
  getFunction(
    nameOrSignature: "permit"
  ): TypedContractMethod<
    [
      token: AddressLike,
      owner: AddressLike,
      spender: AddressLike,
      amount: BigNumberish,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "universalRouter"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Relay"
  ): TypedContractEvent<
    RelayEvent.InputTuple,
    RelayEvent.OutputTuple,
    RelayEvent.OutputObject
  >;

  filters: {
    "Relay(bytes32,address,address,uint256)": TypedContractEvent<
      RelayEvent.InputTuple,
      RelayEvent.OutputTuple,
      RelayEvent.OutputObject
    >;
    Relay: TypedContractEvent<
      RelayEvent.InputTuple,
      RelayEvent.OutputTuple,
      RelayEvent.OutputObject
    >;
  };
}
